package actor

/**
 * @author Amine O.
 * @author Sarah A.
 * 
 * Satellite actor.
 * This class represent a slave drone.
 * the command come from the master drone
 */

import scala.actors._
import scala.actors.Actor
import scala.actors.Actor._
import scala.actors.remote.RemoteActor
import scala.actors.remote.Node
import scala.actors.remote.RemoteActor._
import scaladrone.Drone
import command._

case object Attering
class SatelliteActor(port : Int,name : String) extends Drone with Actor  {

  def getPort = port
  def getName = name
  
  RemoteActor.classLoader = getClass().getClassLoader()
  RemoteActor.alive(port)
  RemoteActor.register('myName, this)
  
  def sendResponse(msg : String){
    sender ! "MESSAGE FROM "+getName+ " : Instruction *"+ msg +"* received and executed !"
  }  

  def act(){
    loop{
      receive {      
        case "test" => println ("ok") 
        sendResponse("test")
        case x : AnimationSimple  => x.execute(this)
        sendResponse("AnimationSimple")
        case x : Attering => x.execute(this) 
        sendResponse("Attering")
        case x : BackByDistance => x.execute(this)
        sendResponse("BackByDistance")
        case x : BackByTime => x.execute(this)
        sendResponse("BackByTime")
        case x : CalculAngleInf45 => x.execute(this)
        sendResponse("CalculAngleInf45")
        case x : CalculAngleSup45 => x.execute(this)
        sendResponse("CalculAngleSup45")
        case x : CalculArcCircl => x.execute(this)
        sendResponse("CalculArcCircl")
        case x : Connect => x.execute(this)
        sendResponse("Connect")
        case x : Disconnect => x.execute(this)
        sendResponse("Disconnect")
        case x : DoCircleHorizontal => x.execute(this)
        sendResponse("DoCircleHorizontal")
        case x : DoCircleVertical => x.execute(this)
        sendResponse("DoCircleVertical")
        case x : DoForwardTurnAroundForward => x.execute(this)
        sendResponse("DoForwardTurnAroundForward")
        case x : DoMovementButterFlyDiagonalForwardLeft => x.execute(this)
        sendResponse("DoMovementButterFlyDiagonalForwardLeft")
        case x : DoMovementButterFlyDiagonalForwardRight => x.execute(this)
        sendResponse("DoMovementButterFlyDiagonalForwardRight")
        case x : DoMovementButterflyForwardBack => x.execute(this)
        sendResponse("DoMovementButterflyForwardBack")
        case x : DoMovementButterflyLeftRight => x.execute(this)
        sendResponse("DoMovementButterflyLeftRight")
        case x : DoMovementEight => x.execute(this)
        sendResponse("DoMovementEight")
        case x : Down => x.execute(this)
        sendResponse("Down")
        case x : DownByDistance => x.execute(this)
        sendResponse("DownByDistance")
        case x : DownByTime => x.execute(this)
        sendResponse("DownByTime")
        case x : ForwardByDistance => x.execute(this)
        sendResponse("ForwardByDistance")
        case x : ForwardByTime => x.execute(this)
        sendResponse("ForwardByTime")
        case x : GoTo => x.execute(this)
        sendResponse("GoTo")
        case x : Initialize => x.execute(this)
        sendResponse("Initialize")
        case x : MoveDiagonalBackDown => x.execute(this)
        sendResponse("MoveDiagonalBackDown")
        case x : MoveDiagonalBackDownByDistance => x.execute(this)
        sendResponse("MoveDiagonalBackDownByDistance")
        case x : MoveDiagonalBackUp => x.execute(this)
        sendResponse("MoveDiagonalBackUp")
        case x : MoveDiagonalBackUpByDistance => x.execute(this)
        sendResponse("MoveDiagonalBackUpByDistance")
        case x : MoveDiagonalForwardDown => x.execute(this)
        sendResponse("MoveDiagonalForwardDown")
        case x : MoveDiagonalForwardDownByDistance => x.execute(this)
        sendResponse("MoveDiagonalForwardDownByDistance")
        case x : MoveDiagonalForwardUp => x.execute(this)
        sendResponse("MoveDiagonalForwardUp")
        case x : MoveDiagonalForwardUpByDistance => x.execute(this)
        sendResponse("MoveDiagonalForwardUpByDistance")
        case x : MoveDiagonalLeftBack => x.execute(this)
        sendResponse("MoveDiagonalLeftBack")
        case x : MoveDiagonalLeftBackTime => x.execute(this)
        sendResponse("MoveDiagonalLeftBackTime")
        case x : MoveDiagonalLeftDown => x.execute(this)
        sendResponse("MoveDiagonalLeftDown")
        case x : MoveDiagonalLeftDownByDistance => x.execute(this)
        sendResponse("MoveDiagonalLeftDownByDistance")
        case x : MoveDiagonalLeftForward => x.execute(this)
        sendResponse("MoveDiagonalLeftForward")
        case x : MoveDiagonalLeftForwardTime => x.execute(this)
        sendResponse("MoveDiagonalLeftForwardTime")
        case x : MoveDiagonalLeftUp => x.execute(this)
        sendResponse("MoveDiagonalLeftUp")
        case x : MoveDiagonalLeftUpByDistance => x.execute(this)
        sendResponse("MoveDiagonalLeftUpByDistance")
        case x : MoveDiagonalRightBack => x.execute(this)
        sendResponse("MoveDiagonalRightBack")
        case x : MoveDiagonalRightBackTime => x.execute(this)
        sendResponse("MoveDiagonalRightBackTime")
        case x : MoveDiagonalRightDown => x.execute(this)
        sendResponse("MoveDiagonalRightDown")
        case x : MoveDiagonalRightDownByDistance => x.execute(this)
        sendResponse("MoveDiagonalRightDownByDistance")
        case x : MoveDiagonalRightForward => x.execute(this)
        sendResponse("MoveDiagonalRightForward")
        case x : MoveDiagonalRightForwardTime => x.execute(this)
        sendResponse("MoveDiagonalRightForwardTime")
        case x : MoveDiagonalRightUp => x.execute(this)
        sendResponse("MoveDiagonalRightUp")
        case x : MoveDiagonalRightUpByDistance => x.execute(this)
        sendResponse("MoveDiagonalRightUpByDistance")
        case x : MoveLeftByDistance => x.execute(this)
        sendResponse("MoveLeftByDistance")
        case x : MoveLeftByTime => x.execute(this)
        sendResponse("MoveLeftByTime")
        case x : MoveRightByDistance => x.execute(this)
        sendResponse("MoveRightByDistance")
        case x : MoveRightByTime => x.execute(this)
        sendResponse("MoveRightByTime")
        case x : Notify => x.execute(this)
        sendResponse("Notify")
        case x : NotifyAll => x.execute(this)
        sendResponse("NotifyAll")
        case x : Ready => x.execute(this)
        sendResponse("Ready")
        case x : SemiCerclBackLeft => x.execute(this)
        sendResponse("SemiCerclBackLeft")
        case x : SemiCerclBackRight => x.execute(this)
        sendResponse("SemiCerclBackRight")
        case x : SemiCerclForwardLeft => x.execute(this)
        sendResponse("SemiCerclForwardLeft")
        case x : SemiCerclForwardRight => x.execute(this)
        sendResponse("SemiCerclForwardRight")
        case x : SemiCerclLeftBack => x.execute(this)
        sendResponse("SemiCerclLeftBack")
        case x : SemiCerclLeftDown => x.execute(this)
        sendResponse("SemiCerclLeftDown")
        case x : SemiCerclLeftForward => x.execute(this)
        sendResponse("SemiCerclLeftForward")
        case x : SemiCerclLeftUp => x.execute(this)
        sendResponse("SemiCerclLeftUp")
        case x : SemiCerclRightBack => x.execute(this)
        sendResponse("SemiCerclRightBack")
        case x : SemiCerclRightDown => x.execute(this)
        sendResponse("SemiCerclRightDown")
        case x : SemiCerclRightForward => x.execute(this)
        sendResponse("SemiCerclRightForward")
        case x : SemiCerclRightUp => x.execute(this)
        sendResponse("SemiCerclRightUp")
        case x : SetAltitudeIfBatteryLow => x.execute(this)
        sendResponse("SetAltitudeIfBatteryLow")
        case x : SetAltitudeMax => x.execute(this)
        sendResponse("SetAltitudeMax")
        case x : SetAltitudeMin => x.execute(this)
        sendResponse("SetAltitudeMin")
        case x : SetEnvironmentIndoor => x.execute(this)
        sendResponse("SetEnvironmentIndoor")
        case x : SetEnvironmentOutdoor=> x.execute(this)
        sendResponse("SetEnvironmentOutdoor")
        case x : SetSpeedHorizontal=> x.execute(this)
        sendResponse("SetSpeedHorizontal")
        case x : SetSpeedVerticalIndoor=> x.execute(this)
        sendResponse("SetSpeedVerticalIndoor")
        case x : SetSpeedVerticalOutdoor=> x.execute(this)
        sendResponse("SetSpeedVerticalOutdoor")
        case x : SetYaw=> x.execute(this)
        sendResponse("SetYaw")
        case x : Simple=> x.execute(this)
        sendResponse("Simple")
        case x : SpeedByTime=> x.execute(this)
        sendResponse("SpeedByTime")
        case x : SpeedListInDoor=> x.execute(this)
        sendResponse("SpeedListInDoor")
        case x : SpeedListOutDoor=> x.execute(this)
        sendResponse("SpeedListOutDoor")
        case x : SpeedVerticalIndoor=> x.execute(this)
        sendResponse("SpeedVerticalIndoor")
        case x : SpeedVerticalOutdoor_$eq=> x.execute(this)
        sendResponse("SpeedVerticalOutdoor_$eq")
        case x : SpeedVerticalOutdoor=> x.execute(this)
        sendResponse("SpeedVerticalOutdoor")
        case x : SquareHorizontal=> x.execute(this)
        sendResponse("SquareHorizontal")
        case x : TakeOff=> x.execute(this)
        sendResponse("TakeOff")
        case x : SquareVertical => x.execute(this)
        sendResponse("SquareVertical")
        case x : TakeOffWithAltitude=> x.execute(this)
        sendResponse("TakeOffWithAltitude")
        case x : Trim => x.execute(this)
        sendResponse("Trim")
        case x : TurnLeftByDegre=> x.execute(this)
        sendResponse("TurnLeftByDegre")
        case x : TurnLeftDown=> x.execute(this)
        sendResponse("TurnLeftDown")
        case x : TurnLeftUp=> x.execute(this)
        sendResponse("TurnLeftUp")
        case x : TurnRightByDegre=> x.execute(this)
        sendResponse("TurnRightByDegre")
        case x : TurnRightDown=> x.execute(this)
        sendResponse("TurnRightDown")
        case x : TurnRightUp=> x.execute(this)
        sendResponse("TurnRightUp")
        case x : Up=> x.execute(this)
        sendResponse("Up")
        case x : UpByDistance=> x.execute(this)
        sendResponse("UpByDistance")
        case x : UpByTime=> x.execute(this)        
        sendResponse("UpByTime")
        case x : Wait=> x.execute(this)
        sendResponse("Wait")
        case unknown => println("MESSAGE from "+ name+" : "+ unknown+" -> command not recognized")

      }
      
    }
    
  }

}